version: 2.1

commands:
  yarn-install:
    description: run `yarn install`
    steps:
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  test:
    docker:
      - image: lts-alpine
        auth:
          username: smarthrinc
          password: $DOCKER_HUB_ACCESS_TOKEN
    steps:
      - checkout
      - yarn-install
      - run: yarn test

workflows:
  version: 2
  build:
    jobs:
      - test:
          context: smarthr-dockerhub
